name: ChallengeCI

on: push

jobs:
  build:
    name: Build go app
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-world
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          go build ${{ env.FILE_NAME }}.go
      - name: Upload the artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}


