name: ChallengeCI

on: push

jobs:
  Test:
    name: Run python script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          python hello-world.py
  Build:
    name: hello world artifact
    runs-on: ubuntu-latest
    needs: [Test]
    env:
      ARTIFACT_NAME: hello-world
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload python artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./{{ env.ARTIFACT_NAME }}
