name: keyword-releaser

on: push

jobs:
  
  Release:
    name: Test a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: adamako/keyword-release-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'FIXED'

